### ISSUE TITLE
coinbase api   Response  http 401

### ISSUE THREAD

**Issue by fumill** [stingbo/easyexchange#110]
coinbase api   Response 401 
密钥已在其他sdk 验证 是正确的；

**Comment by AJ-X** [comment]
> coinbase api Response 401
> 密钥已在其他sdk 验证 是正确的；
如何解决的？

**Comment by stingbo** [comment]
> > coinbase api Response 401
> > 密钥已在其他sdk 验证 是正确的；
> > 如何解决的？

已修复

**Comment by stingbo** [comment]
> coinbase api Response 401
> 密钥已在其他sdk 验证 是正确的；

已修复

**Comment by stingbo** [comment]
升级到v2.0.3即可
