### ISSUE TITLE
http 和https 这里应该填什么？

### ISSUE THREAD

**Issue by secretgao** [stingbo/easyexchange#125]
'proxy' => [
                  //  'http' => 'socks5h://127.0.0.1:1080', // 为 "http" 请求增加代理
                    //'https' => 'socks5h://127.0.0.1:1080', // 为 "https" 请求增加代理
                    'no' => ['.mit.edu', 'foo.com'],   // 不需要使用代理的请求
                ],

**Comment by stingbo** [comment]
这里填写你自己的服务器代理服务，http/https的意思是你的http/https请求会走此对应的代理，no 的意思是 某些请求不走代理

**Comment by stingbo** [comment]
> 'proxy' => [ // 'http' => 'socks5h://127.0.0.1:1080', // 为 "http" 请求增加代理 //'https' => 'socks5h://127.0.0.1:1080', // 为 "https" 请求增加代理 'no' => ['.mit.edu', 'foo.com'], // 不需要使用代理的请求 ],

还有问题吗？没有问题则关闭issue啦
