### ISSUE TITLE
composer 安装你这个失败，用的阿里云的源

### ISSUE THREAD

**Issue by wdwlrz** [stingbo/easyexchange#30]

**Comment by stingbo** [comment]
提示的什么信息能给我看看吗？

**Comment by wdwlrz** [comment]
能获取了。
如果要设置代理，怎么设置呀？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stingbo/easyexchange"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 晚上6:35
收件人:&nbsp;"stingbo/easyexchange"<easyexchange@noreply.github.com&gt;;
抄送:&nbsp;"平淡最真"<774117192@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [stingbo/easyexchange] composer 安装你这个失败，用的阿里云的源 (#30)





 
提示的什么信息能给我看看吗？

**Comment by stingbo** [comment]
目前项目里没有代理的功能，我是在本地使用 Privoxy 进行的代理，或者你使用香港服务器测试。
composer能获取就行，那这个issue我关闭啦

**Comment by wdwlrz** [comment]
ok,thanks




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "stingbo/easyexchange"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月7日(星期天) 晚上9:45
收件人:&nbsp;"stingbo/easyexchange"<easyexchange@noreply.github.com&gt;;
抄送:&nbsp;"平淡最真"<774117192@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [stingbo/easyexchange] composer 安装你这个失败，用的阿里云的源 (#30)





 
目前项目里没有代理的功能，我是在本地使用 Privoxy 进行的代理，或者你使用香港服务器测试。
 composer能获取就行，那这个issue我关闭啦

**Comment by stingbo** [comment]
> ok,thanks
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "stingbo/easyexchange" <notifications@github.com&gt;; 发送时间:&nbsp;2021年3月7日(星期天) 晚上9:45 收件人:&nbsp;"stingbo/easyexchange"<easyexchange@noreply.github.com&gt;; 抄送:&nbsp;"平淡最真"<774117192@qq.com&gt;;"Author"<author@noreply.github.com&gt;; 主题:&nbsp;Re: [stingbo/easyexchange] composer 安装你这个失败，用的阿里云的源 (#30) 目前项目里没有代理的功能，我是在本地使用 Privoxy 进行的代理，或者你使用香港服务器测试。 composer能获取就行，那这个issue我关闭啦 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

现在可以在http请求里增加代理设置了
