### ISSUE TITLE
composer 安装报错，workman 和环境冲突

### ISSUE THREAD

**Issue by wf58585858** [stingbo/easyexchange#86]
环境：
php -v
PHP 7.3.27 (cli) (built: Feb  2 2021 10:32:50) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.27, Copyright (c) 1998-2018 Zend Technologies
    with the ionCube PHP Loader + ionCube24 v10.4.5, Copyright (c) 2002-2020, by ionCube Ltd.
    with Zend OPcache v7.3.27, Copyright (c) 1999-2018, by Zend Technologies
    with Xdebug v2.9.8, Copyright (c) 2002-2020, by Derick Rethans
    with ddtrace v0.55.0, Copyright Datadog, by Datadog

执行命令：
  `composer require "stingbo/easyexchange" -vvv`

报错：
Dependency resolution completed in 0.006 seconds
Reading /root/.cache/composer/repo/https---mirrors.aliyun.com-composer/provider-workerman$workerman.json from cache
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for stingbo/easyexchange ^1.6 -> satisfiable by stingbo/easyexchange[v1.6].
    - stingbo/easyexchange v1.6 requires workerman/workerman dev-master -> satisfiable by workerman/workerman[dev-master] but these conflict with your requirements or minimum-stability.

**Comment by stingbo** [comment]
我修改了使用workman的版本，你再试试
