### ISSUE TITLE
大兄弟，okex Websocket 里没有封装私人频道的接口调用吗？

### ISSUE THREAD

**Issue by wf58585858** [stingbo/easyexchange#94]
我计划的是使用 Websocket 来完成所有逻辑，没考虑使用 http接口，如果 Websocket  能满足的话

我看你这个类里面，就只封装了 /ws/v5/public 的请求，没做 /ws/v5/private 的封装？
\EasyExchange\Okex\Websocket\Client

啥时候能不能考虑把这个私人的数据也封装进去

https://www.okex.win/docs-v5/zh/?java#overview-production-trading-services

给个参考的
https://github.com/zhouaini528/okex-php
最底下， websocket 部分，类似那样可以调用私人接口的

**Comment by wf58585858** [comment]
感激不尽！

**Comment by stingbo** [comment]
OK，我尽快

**Comment by stingbo** [comment]
> 感激不尽！

OK，我尽快

**Comment by wf58585858** [comment]
有没有qq群啥的

**Comment by stingbo** [comment]
> 没有qq群啥的

刚创建了一个QQ群，871358160，因为是业余时间在维护项目，所以上班时间回复不及时，请见谅

**Comment by stingbo** [comment]
okex已更新
